# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: includes
  pool: 20
  username: root
  password: Nfh8dDs1kzx8

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: includes_test
  pool: 5
  username: root
  password: Nfh8dDs1kzx8

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: includes
  pool: 20
  username: root
  password: Nfh8dDs1kzx8

