require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncludesController do

  # This should return the minimal set of attributes required to create a valid
  # Include. As you add validations to Include, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncludesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all includes as @includes" do
      include = Include.create! valid_attributes
      get :index, {}, valid_session
      assigns(:includes).should eq([include])
    end
  end

  describe "GET show" do
    it "assigns the requested include as @include" do
      include = Include.create! valid_attributes
      get :show, {:id => include.to_param}, valid_session
      assigns(:include).should eq(include)
    end
  end

  describe "GET new" do
    it "assigns a new include as @include" do
      get :new, {}, valid_session
      assigns(:include).should be_a_new(Include)
    end
  end

  describe "GET edit" do
    it "assigns the requested include as @include" do
      include = Include.create! valid_attributes
      get :edit, {:id => include.to_param}, valid_session
      assigns(:include).should eq(include)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Include" do
        expect {
          post :create, {:include => valid_attributes}, valid_session
        }.to change(Include, :count).by(1)
      end

      it "assigns a newly created include as @include" do
        post :create, {:include => valid_attributes}, valid_session
        assigns(:include).should be_a(Include)
        assigns(:include).should be_persisted
      end

      it "redirects to the created include" do
        post :create, {:include => valid_attributes}, valid_session
        response.should redirect_to(Include.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved include as @include" do
        # Trigger the behavior that occurs when invalid params are submitted
        Include.any_instance.stub(:save).and_return(false)
        post :create, {:include => { "name" => "invalid value" }}, valid_session
        assigns(:include).should be_a_new(Include)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Include.any_instance.stub(:save).and_return(false)
        post :create, {:include => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested include" do
        include = Include.create! valid_attributes
        # Assuming there are no other includes in the database, this
        # specifies that the Include created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Include.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => include.to_param, :include => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested include as @include" do
        include = Include.create! valid_attributes
        put :update, {:id => include.to_param, :include => valid_attributes}, valid_session
        assigns(:include).should eq(include)
      end

      it "redirects to the include" do
        include = Include.create! valid_attributes
        put :update, {:id => include.to_param, :include => valid_attributes}, valid_session
        response.should redirect_to(include)
      end
    end

    describe "with invalid params" do
      it "assigns the include as @include" do
        include = Include.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Include.any_instance.stub(:save).and_return(false)
        put :update, {:id => include.to_param, :include => { "name" => "invalid value" }}, valid_session
        assigns(:include).should eq(include)
      end

      it "re-renders the 'edit' template" do
        include = Include.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Include.any_instance.stub(:save).and_return(false)
        put :update, {:id => include.to_param, :include => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested include" do
      include = Include.create! valid_attributes
      expect {
        delete :destroy, {:id => include.to_param}, valid_session
      }.to change(Include, :count).by(-1)
    end

    it "redirects to the includes list" do
      include = Include.create! valid_attributes
      delete :destroy, {:id => include.to_param}, valid_session
      response.should redirect_to(includes_url)
    end
  end

end
